### ISSUE TITLE
Bug in removing non-empty temp directory

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/php-temp#3]
`FileSystem::remove()` could remove non-empty directories unlike `rmdir()` function
(https://github.com/keboola/php-temp/commit/d76fc44d38c804565d8d13621ef9e1be27a49540#diff-b88a976e1fcdb795dd34382000376388L176)

**Comment by JakubMatejka** [comment]
ping

**Comment by ondrejhlavacek** [comment]
@JakubMatejka Is this still an issue? If so, can you please create a failing test with the intended behavior? Thanks!

**Comment by odinuv** [comment]
can't reproduce, closing
